### ISSUE TITLE
IOS: Data picker "Confirm" button isn't clickable in some special case

### ISSUE THREAD

**Issue by LowerShotower** [mmazzarolo/react-native-modal-datetime-picker#357] opened 2020-02-03 13:08 UTC
-Open Calendar and push on selected data or try to select another day (important point that you should not swipe dates, only click on dates)

-Try to Click on Confirm button => it will not react
Here is the link on video example 
https://drive.google.com/file/d/1U96zmdoO2H-wtswY9YCoZzGz0BBbyavU/view

**Comment by mmazzarolo** [comment] 2020-02-04 12:49
Hey @LowerShotower , could you please provide a minimal reproducible example/repo? 
Does it happens with the example (in the example dir)?

**Comment by LowerShotower** [comment] 2020-02-05 13:12
Hello @mmazzarolo ,  I've tested it, and yep, I have the same problem with example/repo

**Comment by LowerShotower** [comment] 2020-02-05 13:21
Want clarify if it was not clear. I tap on date, and after that i can't click on Confirm. It doesn't react for some reason

**Comment by fstojanac** [comment] 2020-02-05 14:49
I had opened [PR](https://github.com/mmazzarolo/react-native-modal-datetime-picker/pull/361) that should fix this.

**Comment by mmazzarolo** [comment] 2020-02-05 16:45
@LowerShotower thanks for reporting. 

I can't test it now, but I'm wondering if it's a race condition caused by [this check](https://github.com/mmazzarolo/react-native-modal-datetime-picker/blob/a34728a1495bcaa926bf753542ed66e276179c50/src/DateTimePickerModal.ios.js#L135), that is made to disable the confirm button until it stops spinning 🤔

**Comment by fstojanac** [comment] 2020-02-05 16:55
@mmazzarolo I had tested that, this is not the case, at least not for me.

**Comment by mmazzarolo** [comment] 2020-02-05 17:12
Thanks @fstojanac 
Does the issue happen only when you tap the date (instead of spinning ) for you?

**Comment by LowerShotower** [comment] 2020-02-06 04:53
Yes, After I tap on the selected date, I can't click on the Confirm button, but I still can click on the Cancel button. Also, if I first scroll dates and after that click on the selected date, the Confirm button also doesn't work. And if select date by scrolling the wheel, all works fine. It happens on the real devices too

**Comment by LowerShotower** [comment] 2020-02-06 07:11
The version of datetime-picker:  "react-native-modal-datetime-picker": "^7.6.1",

**Comment by LowerShotower** [comment] 2020-02-12 14:17
tested with react-native-modal-datetime-picker. still doesn't work

**Comment by mmazzarolo** [comment] 2020-02-12 16:43
Mind trying the following?
```
```

**Comment by mmazzarolo** [comment] 2020-02-12 16:47
Mind trying the following and report if it's working?

```js
// Define a custom confirm button component (so that it should always be enabled)
const CustomConfirmButton = ({ onPress }) => {
  return (
    <TouchableHighlight onPress={onPress}>
      <Text>I should work</Text>
    </TouchableHighlight>
  );
};

// And pass it to the `react-native-modal-datetime-picker` component
```js
<DateTimePickerModal
        isVisible={isDatePickerVisible}
        mode="date"
        onConfirm={handleConfirm}
        onCancel={hideDatePicker}
       customConfirmButtonIOS={CustomConfirmButton}
/>
```

**Comment by cameronbell** [comment] 2020-02-12 20:49
Experiencing the same issue. The CustomConfirmButton works in my case.

**Comment by mmazzarolo** [comment] 2020-02-13 08:56
Thanks for reporting @cameronbell .
At this point I guess that [this part of the code](https://github.com/mmazzarolo/react-native-modal-datetime-picker/blob/a34728a1495bcaa926bf753542ed66e276179c50/src/DateTimePickerModal.ios.js#L135) is not working correctly. 
The reason why we had that check, is because the native IOS DateTimePicker sometimes does not report the correct date/time until the the rolling animation ends (see [this issue](https://github.com/facebook/react-native/issues/8169)). 
As a workaround, we were manually disabling the "Confirm" button until the rolling completed... but this doesn't seem to be working anymore if you just "press" directly on a date (probably a timing conflict between the disable/date picking).  

At this point I guess we have to remove the disabling logic (or make it an opt-in? doesn't make much sense though).

**Comment by mmazzarolo** [comment] 2020-02-13 08:59
I've also noticed some new activity in the [`react-native-community/react-native-datetimepicker`](https://github.com/react-native-community/react-native-datetimepicker/pulls?q=is%3Apr+is%3Aclosed) repo, not sure if something changed on their end recently.

**Comment by sallar** [comment] 2020-02-14 08:11
I'm also having this issue. I implemented custom Confirm and Cancel buttons, it works, but sometimes those lock up as well. But if I remove all the styling, then it always works.

```tsx
const ConfirmButtonWrapper = styled.TouchableHighlight`
  height: 57px;
  border-top-width: ${StyleSheet.hairlineWidth}px;
  background-color: transparent;
  justify-content: center;
`;

const ConfirmButtonText = styled.Text`
  color: ${p => p.theme.colors.primary};
  text-align: center;
  font-size: 20px;
`;

const CancelButtonWrapper = styled.TouchableHighlight`
  height: 57px;
  background-color: ${p => (p.theme.dark ? '#0E0E0E' : '#fff')};
  justify-content: center;
  border-radius: 13px;
  margin-bottom: ${isIphoneX() ? 20 : 0}px;
`;

const CancelButtonText = styled(ConfirmButtonText)`
  font-weight: 600;
`;

const ConfirmButton: ConfirmButtonComponent = ({ onPress, label }) => {
  const theme = useTheme();

  return (
    <ConfirmButtonWrapper
      onPress={onPress}
      underlayColor={theme.dark ? '#444' : '#ebebeb'}>
      <ConfirmButtonText>{label}</ConfirmButtonText>
    </ConfirmButtonWrapper>
  );
};

const CancelButton: CancelButtonComponent = ({ onPress, label }) => {
  const theme = useTheme();

  return (
    <CancelButtonWrapper
      onPress={onPress}
      underlayColor={theme.dark ? '#444' : '#ebebeb'}>
      <CancelButtonText>{label}</CancelButtonText>
    </CancelButtonWrapper>
  );
};

const DatePicker: React.FunctionComponent<DateTimePickerProps> = props => {
  return (
    <DateTimePickerModal
      {...props}
      customConfirmButtonIOS={ConfirmButton}
      customCancelButtonIOS={CancelButton}
    />
  );
};

export default DatePicker;
```

**Comment by mmazzarolo** [comment] 2020-02-15 14:00
Hey all, anyone willing to try #370 ?

**Comment by sallar** [comment] 2020-02-15 15:51
@mmazzarolo I think this is a good way to solve it. It's pretty unlikely that the user taps on confirm before the spinner stops spinning

**Comment by mmazzarolo** [comment] 2020-02-15 16:04
@sallar I hope so! The reason why we added that feature (ages ago) was specifically because users were pressing "Confirm" before it stopped spinning, lol. 
That said, there's not much we can do about that, it happens even if you play with the native clock/timer app on iOS 🤷

**Comment by livefuture009** [comment] 2020-02-18 09:08
I am getting same error. I had upgraded to latest version. But same issue :( is there any solve way?

**Comment by mmazzarolo** [comment] 2020-02-18 09:22
@livefuture009 could you please try the PR I posted above?

`yarn add mmazzarolo/react-native-modal-datetime-picker#370/head && react-native start -- --reset-cache`

Let me know if it works for you, so that I can publish it officially

**Comment by tannguyen16** [comment] 2020-02-20 17:46
Thanks @mmazzarolo for the package!
I'm having the same issue by tapping the date and tap "Confirm" button. If I try your PR, do I need to `import DatePicker from 'mmazzarolo/react-native-modal-datetime-picker#370/head'`?

**Comment by mmazzarolo** [comment] 2020-02-20 17:47
You should always use the default import 👍

**Comment by tannguyen16** [comment] 2020-02-20 20:25
Hi @mmazzarolo, 

I'm trying the PR but having some issues. After running yarn add, my package.json has changed to 
`"react-native-modal-datetime-picker": "mmazzarolo/react-native-modal-datetime-picker#370/head"`
However, it still gave me an error:
`Unable to resolve "react-native-modal-datetime-picker"`
I've tried removing node_modules and run npm install again but still didn't work. Do I miss anything in the process?

Thanks!

**Comment by mmazzarolo** [comment] 2020-02-21 08:05
@tannguyen16 I just release `v8.3.0` with the included fix

**Comment by samslow** [comment] 2020-02-23 13:39
@mmazzarolo  `v8.3.0` There is still the same problem. i can't click both confirm and cancel

**Comment by mmazzarolo** [comment] 2020-02-23 20:50
Can you try the example app? 
Also, when is the issue happening for you?
I just tried it and it seems to be working fine for me. 
Make sure to reset the server. 

![2020-02-23 21 50 05](https://user-images.githubusercontent.com/9536354/75119801-88dcce80-5686-11ea-8b30-81b32eed2f78.gif)

![2020-02-23 21 48 06](https://user-images.githubusercontent.com/9536354/75119781-5337e580-5686-11ea-87c2-46999a474bba.gif)

**Comment by samslow** [comment] 2020-02-24 05:24
![image](https://user-images.githubusercontent.com/26738367/75130321-149b3d00-5711-11ea-834d-f8636fa8808e.png)
`Dimentions.get("window")`→ `dimentionsUpdate`

it's work after modify by @fstojanac code in my code like above's

**Comment by mmazzarolo** [comment] 2020-02-24 06:31
@samslow I merged that PR as well since it seems to solve the issue for your use cases. 
The example seems to be running fine for me (and for the others above) without it, so I guess it might be something related to the app config in your case. 
It would be interesting if you could try it on the example code if you have a minute before updating, to understand where the issues lies.

**Closed** 2020-02-24 06:32 UTC
Labels: bug, waiting for feedback

**Comment by SudoPlz** [comment] 2021-03-19 22:28
@mmazzarolo I assume we're back to that old bug of getting the wrong datetime if the user taps confirm too fast... So it sounds like in order to resolve a UI issue we exposed a functionality issue again.
😞

**Comment by mmazzarolo** [comment] 2021-03-19 22:40
@SudoPlz I think what you're mentioning is the issue that happens when you pick a date while scrolling the component -- which is a different issue from this one, right?

**Comment by SudoPlz** [comment] 2021-03-19 22:41
Yep definitely different issues, but "fixing" this one, brought back that old bug, right?

**Comment by mmazzarolo** [comment] 2021-03-19 22:45
@SudoPlz Yeah, what I mean is: AFAIK, there's no way to solve this issue correctly without introducing other small UX bugs (the spinner fix also had other issue that were reported before this one) -- because, unfortunately, this buggy behaviour is something that happens at the native level. So, instead of patching it here and causing other issues, we just go straight with the current behaviour :/ 
My take on this: it should be solved either natively or in the community picker.

**Comment by SudoPlz** [comment] 2021-03-19 22:47
Got it, that makes sense. Is there an issue open on the community picker right now? Do you know? They're probably not even aware of that super old bug.

**Comment by mmazzarolo** [comment] 2021-03-19 22:56
No idea 🤷
I still have this old thread bookmarked though, lol: https://github.com/facebook/react-native/issues/8169

Maybe we can also add this info in the FAQs of the component? 

Let me know if you find a related issue.

**Comment by SudoPlz** [comment] 2021-03-19 23:04
Yeah we should definitely add that to the FAQ. I'm currently trying to resolve the issue on the native side, but it looks difficult now that the `uiManager` access is removed from react-native :/ I'll keep trying.

**Comment by SudoPlz** [comment] 2021-03-20 00:23
I wonder if this line of code was put there to fix that exact issue: https://github.com/react-native-datetimepicker/datetimepicker/blob/8ccb07ace9d3a5df9cf33f4f476325247cb6372c/src/datetimepicker.ios.js#L69

**Comment by SudoPlz** [comment] 2021-03-20 02:54
@mmazzarolo ok I worked around the issue using a native method addition.
I created two patches for this:
https://gist.github.com/SudoPlz/6959001879fbfcc7e2aa42a428a5265c

**Comment by mmazzarolo** [comment] 2021-03-20 09:35
@SudoPlz Amazing 🙌

**Comment by mmazzarolo** [comment] 2021-03-20 09:42
https://github.com/mmazzarolo/react-native-modal-datetime-picker/blob/master/README.md#the-date-in-onconfirm-doesnt-match-the-picked-date-on-ios

**Comment by jahnav0066** [comment] 2024-01-09 08:42
I'm facing the same issue differently. I'm using a date picker in the Flatlist renderitem component.
When I search on searchbar for a product and click on enter and then try to open and set the date picker will open 1st time but the date will not be set.
