### ISSUE TITLE
react-native-modal-datetime-picker not working with react-native-modal 9.0.0

### ISSUE THREAD

**Issue by SystemBlad** [mmazzarolo/react-native-modal-datetime-picker#223] opened 2019-02-25 13:57 UTC
After install the react-native-modal 9.0.0 the following error is displayed:

Loading dependency graph, done.
error: bundling failed: Error: Unable to resolve module `./animations` from `node_modules\react-native-modal\src\index.js`: The module `./animations` could not be found from `\node_modules\react-native-modal\src\index.js`. Indeed, none of these files exist: \node_modules\react-native-modal\src\animations

The error is presented because react-native-modal-datetime-picker  is using "react-native-modal": "6.2.0".

react-native-modal-datetime-picker: "6.0.0"
react-native-modal: 9.0.0
react-native: "0.58.5"

**Comment by mmazzarolo** [comment] 2019-03-13 08:49
Seems to be working fine for me.
Could you please provide a repo with a reproducible issue?

**Comment by SystemBlad** [comment] 2019-03-13 16:18
Hi @mmazzarolo.  
The repo is in github:  https://github.com/SystemBlad/RNDatetimePickerBug.git
To reproduce follow the next steps:

1 Clone the repository and run npm install
2 Run react-native run-android and see the two buttons with no action when they are pressed.
3 Run npm install  --save react-native-modal-datetime-picker
3 Uncomment commented code in App.js file
3 Run react-native run-android and now the two buttons show the modals.
4 Run npm install  --save react-native-modal
5 Run react-native run-android and the Bug is presented.

**Comment by mmazzarolo** [comment] 2019-03-13 18:59
Thank you 🙏 
I’ll check it soon but since you’re using both modals the issue might just be solvable by bumping the RN version number of react native datetime picker.

**Comment by mmazzarolo** [comment] 2019-03-15 13:00
@SystemBlad should be fixed by https://github.com/mmazzarolo/react-native-modal-datetime-picker/pull/225, wanna give it a try?

**Comment by SystemBlad** [comment] 2019-03-15 17:42
Hi @mmazzarolo,  is working perfect with master branch that is using "react-native-modal": "^9.0.0".

Thank you very much

**Comment by mmazzarolo** [comment] 2019-03-15 21:13
Published in `6.1.0`! Thanks @SystemBlad for helping out and for the quick feedbacks!

**Closed** 2019-03-19 10:29 UTC

**Comment by helloeyesimple** [comment] 2019-04-28 19:26
I'm using 7.4.0 and the issue is back. It cannot show the modal again after setState to false.
Not sure if this is the same issue or not.
