### ISSUE TITLE
display mode forced to IOS 14 "compact"

### ISSUE THREAD

**Issue by dakairus** [mmazzarolo/react-native-modal-datetime-picker#533] opened 2021-02-27 10:06 UTC
## Platforms

IOS 14 only

## Versions

7.6.1

## Description

react native modal datetime picker is defaulting the "display" of the picker in IOS to the new "compact" display mode. I tried to include the "display" = "spinner" property into the modal without success.

Included the latest version of the modal datetime picker as well as @react-native-community/datetimepicker as suggested in https://github.com/mmazzarolo/react-native-modal-datetime-picker#the-picker-is-not-showing-the-right-layout-on-ios--14.

Including directly the @react-native-community/datetimepicker as a component and adding the display = "spinner" works perfectly, so seems there some sort of override in the modal that specifying the field is not passed down to the @react-native-community/datetimepicker.

**Comment by mmazzarolo** [comment] 2021-02-27 10:25
Hi!

> react native modal datetime picker is defaulting the "display" of the picker in IOS to the new "compact" display mode

[We are setting it to `spinner`](https://github.com/mmazzarolo/react-native-modal-datetime-picker/blob/4e4822f8e6ffb2603231c4017a45c1b67de1b0c4/src/DateTimePickerModal.ios.js#L154). 

Closing because we still haven't got a single case of reproducible example in reports of this issues yet -- they were all caused by conflicting versions/cache.

Feel free to re-create a new issue if needed (following the issue template + a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) please 🙏)

**Closed by mmazzarolo** 2021-02-27 10:25 UTC
Labels: bug
