### ISSUE TITLE
`DeviceEventEmitter.removeListener` is not supported on React Native 0.70+

### ISSUE THREAD

**Issue by fansilva1991** [mmazzarolo/react-native-modal-datetime-picker#681] opened 2023-01-04 20:21 UTC
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `react-native-modal-datetime-picker@9.2.3` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/react-native-modal-datetime-picker/src/Modal.js b/node_modules/react-native-modal-datetime-picker/src/Modal.js
index 6e5f95d..1466d08 100644
--- a/node_modules/react-native-modal-datetime-picker/src/Modal.js
+++ b/node_modules/react-native-modal-datetime-picker/src/Modal.js
@@ -48,10 +48,12 @@ export class Modal extends Component {
   }
 
   componentWillUnmount() {
-    DeviceEventEmitter.removeListener(
-      "didUpdateDimensions",
-      this.handleDimensionsUpdate
-    );
+    try {
+      DeviceEventEmitter.removeListener(
+        "didUpdateDimensions",
+        this.handleDimensionsUpdate
+      );
+    } catch (e) {} 
     this._isMounted = false;
   }
 
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by fansilva1991** [comment] 2023-01-04 20:23
Looks like this is happening because ```DeviceEventEmitter.removeListener``` has been removed after being deprecated for a while.

**Comment by joe-brabben** [comment] 2023-01-11 11:22
@mmazzarolo Hi any updates on this being landed as it is currently crashing devices. Thanks

**Comment by mmazzarolo** [comment] 2023-01-16 15:58
Hey I'm currently on parental leave and can't work directly on the codebase. If you're willing to update #669 adding support [for the updated Dimensions API](https://reactnative.dev/docs/dimensions) I can give it a review and try it out.

**Comment by joe-brabben** [comment] 2023-01-24 11:12
@mmazzarolo Hey sorry for the delay was busy on new native version for a bit. I've submitted the pull request now so should all be good. Thanks

**Comment by khzouroussama** [comment] 2023-03-16 09:31
@fansilva1991 this will be fixed if you update the library, there is no need for this patch, the deprecated API `DeviceEventEmitter.removeListener` has been already replaced with `listener.remove()`

@mmazzarolo I don't think we need to do any change here

**Comment by mmazzarolo** [comment] 2023-03-16 09:47
@khzouroussama not sure I'm following, who replaced `DeviceEventEmitter.removeListener` with `listener.remove()`? 👀 It's still here in this lib.

**Comment by khzouroussama** [comment] 2023-03-16 10:26
I believe it was changed here https://github.com/mmazzarolo/react-native-modal-datetime-picker/pull/591
I was facing the same issue before because my app was on an older version, so it is not reproducible on the recent versions

**Comment by mmazzarolo** [comment] 2023-03-16 10:32
Ah, right, I thought this issue was about something different. Good call, thanks!

**Closed by mmazzarolo** 2023-03-16 10:32 UTC
Labels: bug, help wanted, great first issue!

**Comment by joe-brabben** [comment] 2023-03-16 10:40
@mmazzarolo sounds fixed. Want me to close the pull request???

**Comment by hamdidamar** [comment] 2023-03-21 07:55
> @mmazzarolo sounds fixed. Want me to close the pull request???

Yes please. i still get the some error on ios devices because of this.
