### ISSUE TITLE
when mode props value is ‘date time’, to select ‘time’ and click cancel button would be invalid. 

### ISSUE THREAD

**Issue by fangshifeng** [mmazzarolo/react-native-modal-datetime-picker#30] opened 2017-04-13 03:27 UTC
Solution: modify index.js

TimePickerAndroid.open(timeOptions).then(({action, minute, hour}) => {
            if (action === TimePickerAndroid.timeSetAction) {
              let selectedDate = new Date(year, month, day, hour, minute);
              this.props.onConfirm(selectedDate);
            } else {
              this.props.onCancel()
            }
          });

**Comment by mmazzarolo** [comment] 2017-04-13 18:14
Hey!
[I just commited a fix](https://github.com/mmazzarolo/react-native-modal-datetime-picker/commit/4181d27130d50b0b61422702293a19b389540d46), could you give it a shot and tell me if it works for you?  
I'll push it to npm then :)  
Thanks man!

**Comment by fangshifeng** [comment] 2017-04-17 01:37
very well！

**Comment by lhr000lhr** [comment] 2017-05-22 05:55
it does not work.

**Comment by mmazzarolo** [comment] 2017-05-23 04:47
I'm reopening, could you provide an example sto that I can reproduce it?
What are you using? iOS or Android?

**Comment by lhr000lhr** [comment] 2017-05-23 08:36
android ， i have to write like this to prevent bug
 ```   
<DateTimePicker
                                            isVisible={this.state.isEndDateTimePickerVisible}
                                            mode='datetime'
                                            onConfirm={(date) => {
                                                this.setState({
                                                    isEndDateTimePickerVisible: false
                                                });

                                                if (!(date instanceof Date) || !isFinite(date)) {
                                                    return;
                                                }



                                                let time = Moment(date);
                                                this.setState({
                                                    endTime: time

                                                });

                                            }}
                                            onCancel={() => {
                                                this.setState({
                                                    isEndDateTimePickerVisible: false
                                                });
                                            }}
                                        />
```

**Comment by mmazzarolo** [comment] 2017-05-24 12:13
@lhr000lhr it is still working correctly for me even while removing that "fix" on a Nexus5X (language Italian). 
What model is you device? 
Is it an emulator? 
What's the language you set? 
And what is its Android version?

**Comment by lhr000lhr** [comment] 2017-05-24 15:03
i have tested in serveral devices containing android 4.1 - 6.0 .It's really easy to recurrence this bug. i'd like to commit a demo,if it's helpful to fix it.

**Comment by lhr000lhr** [comment] 2017-05-24 15:09
here is that page's source code. thers is nothing special,but the bug comes every time.
[MeetingEditTime.js.zip](https://github.com/mmazzarolo/react-native-modal-datetime-picker/files/1026010/MeetingEditTime.js.zip)

**Comment by mmazzarolo** [comment] 2017-05-24 15:11
I have a feeling this bug is caused by the language of your system, could you try with a device in english language?

**Comment by lhr000lhr** [comment] 2017-05-24 15:27
this emulator is in English.

**Comment by mmazzarolo** [comment] 2017-05-24 15:52
I might have fixed it, could you try the version in the master branch?
Still don't know why it did work on other devices though... 🤔

**Comment by mmazzarolo** [comment] 2017-05-26 07:34
@lhr000lhr did you test? I'd like to close this issue :)

**Comment by lhr000lhr** [comment] 2017-05-26 16:27
no yet. i'll test it as soon as possible._(:з」∠)_

**Comment by mmazzarolo** [comment] 2017-06-04 20:35
Closing, let me know if the issue arises again 👍

**Closed by mmazzarolo** 2017-06-04 20:35 UTC
