### ISSUE TITLE
iOS: The Confirm button stays disabled on singe tap (no drag)

### ISSUE THREAD

**Issue by zubko** [mmazzarolo/react-native-modal-datetime-picker#82] opened 2017-08-30 05:29 UTC
Using latest: v4.10.0

The button become disabled on `onStartShouldSetResponderCapture`, but then the value didn't change, so the button doesn't become enabled.

I've tried to put the handler to `onMoveShouldSetResponderCapture`, at least it's triggered when some movement happens. It's still possible that Confirm will stay disabled but the margin for error is smaller. Single taps won't cause the issue.

Ideally I think the button should become disabled when the drag distance is big enough, but unfortunately I don't have time for finetunning a 100% fix and PR, so I'm just reporting.

**Comment by mmazzarolo** [comment] 2017-08-30 17:22
@zubko thank you for the report, I'll take a look at it as soon as I have some free time.  
Anyone else having the same issue?

**Comment by thurber** [comment] 2017-10-13 21:38
I'm also experiencing this issue... if a user taps on the value that is already selected, the confirm button remains disabled until they change the value.

What's the reason for disabling the confirm button at all?

**Comment by mmazzarolo** [comment] 2017-10-17 10:33
@thurber might be related to #40, what do you think?

**Comment by thurber** [comment] 2017-10-17 13:51
I see, so it prevents confirming while the wheel is actively in motion, so that an old value isn't confirmed. That makes sense, but unfortunately my users are getting confused. ^_^;

Any chance you'd be open to adding a prop to disable this behavior? I'd be happy to PR it.

**Comment by mmazzarolo** [comment] 2017-10-17 13:53
Of course! Just remember to not update the README.md

**Comment by mmazzarolo** [comment] 2017-10-18 16:53
Should be fixed in the new [v4.13.0](https://github.com/mmazzarolo/react-native-modal-datetime-picker/releases/tag/v4.13.0)

**Closed by mmazzarolo** 2017-10-18 16:53 UTC
Labels: bug
